language: python
python:
  - "2.7"
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
script: nosetests

env:
  global:
    - "FTP_USER=user"
    - "FTP_PASSWORD=password"
after_success:
  - eval "$(ssh-agent -s)" #start the ssh agent
  - chmod 600 .travis/pythonanywhere_key.pem # this key should have push access
  - ssh-add .travis/pythonanywhere_key.pem
  - git push pythonanywhere