language: python
python:
  - "2.7"
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
script: nosetests

before_script: 
  - echo -e "Host *\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

after_success:
  - git config --
  - git remote add pythonanywhere abdulachik:aa121292@ssh.pythonanywhere.com:/home/abdulachik/bare-repos/abdul-blog-2016.git
  - git push pythonanywhere